# Generated by Django 6.0.2 on 2026-02-13 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MockInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(help_text='e.g. Python Backend, Frontend React, Data Structures', max_length=200)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=45)),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Interviewer notes during the session', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mock_interviews', to='companies.company')),
                ('interviewer', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['ADMIN', 'ALUMNI']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mock_interviews_as_interviewer', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='mock_interviews_as_student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_score', models.IntegerField(default=0, help_text='Scale 1-10')),
                ('communication_score', models.IntegerField(default=0, help_text='Scale 1-10')),
                ('behavioral_score', models.IntegerField(default=0, help_text='Scale 1-10')),
                ('problem_solving_score', models.IntegerField(default=0, help_text='Scale 1-10')),
                ('strengths', models.TextField()),
                ('areas_of_improvement', models.TextField()),
                ('overall_comments', models.TextField()),
                ('is_ready_for_real_interview', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='mock_interviews.mockinterview')),
            ],
        ),
    ]
