# Generated by Django 6.0.2 on 2026-02-13 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mock_interviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InterviewFeedback',
            new_name='MockInterviewFeedback',
        ),
    ]
