# Generated by Django 6.0.2 on 2026-02-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewfeedback',
            name='core_technical_topics',
            field=models.TextField(blank=True, help_text='Comma separated topics like React, AWS, OS', null=True),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='culture_fit_advice',
            field=models.TextField(blank=True, help_text='What is the company culture like?', null=True),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='rounds_count',
            field=models.IntegerField(default=1, help_text='Total number of rounds'),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='salary_package',
            field=models.CharField(blank=True, help_text='e.g. 12 LPA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='interviewfeedback',
            name='tips',
            field=models.TextField(blank=True, help_text='General preparation advice', null=True),
        ),
    ]
