# Generated by Django 6.0.2 on 2026-02-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_interviewfeedback_core_technical_topics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewfeedback',
            name='interview_type',
            field=models.CharField(choices=[('TECH', 'Technical'), ('HR', 'HR'), ('BOTH', 'Technical + HR'), ('MNG', 'Managerial')], default='TECH', max_length=4),
        ),
        migrations.AddField(
            model_name='interviewfeedback',
            name='placement_type',
            field=models.CharField(choices=[('ON', 'On-Campus'), ('OFF', 'Off-Campus'), ('REF', 'Referral'), ('INT', 'Internal/Other')], default='ON', max_length=3),
        ),
    ]
