# Generated by Django 6.0.2 on 2026-02-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('website', models.URLField(blank=True, null=True)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('industry', models.CharField(max_length=100)),
                ('min_cgpa', models.FloatField(default=0.0)),
                ('required_skills', models.TextField(help_text='Comma separated skills')),
                ('recruitment_drive_date', models.DateField(blank=True, null=True)),
                ('ctc_range', models.CharField(help_text='e.g. 5-8 LPA', max_length=100)),
                ('active_hiring', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
